# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CocoaFrameWorks_ClassExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    pod 'GoogleMaps'
    pod 'AFNetworking', '~> 3.0'
    pod 'Alamofire', '~> 4.4'

  # Pods for CocoaFrameWorks_ClassExample

end
